### PR TITLE
Fix: Use `codecov/codecov-action` to report coverage to `codecov.io`

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] uses [`codecov/codecov-action`](https://github.com/codecov/codecov-action) to report coverage to `codecov.io`

### CODE REVIEW

**Comment by theseer** [comment]
@localheinz However that happend: The Pipeline after the merge is now broken again...?

**Comment by localheinz** [comment]
@theseer 

I'll take a 👀!

**Comment by theseer** [comment]
While you're at it: I temporarily switched to using the action's `tools` keyword to install phpunit. While I don't understand how that can fail on macos but work on linux, I also dislike the fact that's a 2nd place where the phpunit version is managed. I would thus like to have it installed via phive again ;)

**Comment by localheinz** [comment]
@theseer 

Looks like a temporary issue: https://github.com/phar-io/manifest/runs/5264996332?check_suite_focus=true#step:3:15.

**Pull request merged**
